Delete button and misc
Wcarey7/KillawattElectrical pull request #11
Opened 2023-12-15 01:17 UTC by Wcarey7

- Delete customer modal. Confirmation modal now pops up when delete button is clicked. Page reloads after each delete, if the last row is deleted the previous page is loaded.

- Favicon image Located in the static folder. Image shows up on the tab in the web browser, the little icon next to the title. Gets rid of the 404 code for the favicon in the console.

- Removed debug toolbar extension. No longer needed, it flooded the console with many GET requests, and sometimes failed.

- user_profile folder. Moved the user_profile.html.j2 into its own folder under templates.

- Re-work of the error template pages for the 404 and 500 HTTP error codes. They previously weren't being rendered if called from certain routes. Text is now centered.

- Flashed messages (i.e. "You Are Now Logged In", "New Customer Added") now slide up and dismiss after 3 seconds.

- Switched to using the shorthand CSS method of grid-column and grid-row.

- Consistent use of single/double quotes and more descriptive css/html class names.

2023-12-20 17:33 UTC, jdstone requested changes
This looks like the same PR as #10.  Let's review this together as well.  Let me know when you're available.

2023-12-20 20:01 UTC, Wcarey7 commented
> This looks like the same PR as #10. Let's review this together as well. Let me know when you're available.

Its the same. Around 6pm today?

2023-12-21 15:13 UTC, jdstone commented
Sorry, I thought you would text me.

2023-12-22 00:03 UTC, jdstone approved these changes

2023-12-22 00:03 UTC, merged